version: 2.1

orbs:
  bridgecrew: bridgecrew/bridgecrew@1.0.5

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python main.py
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python tests.py
  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - run: echo "Deploying to production server"
  checkov:
    executor: checkov/default
    steps:
      - checkout
      - checkov/scan:
          directory: .
          api-key-variable: BC_API_KEY
          prisma-api-url: https://api.prismacloud.io

workflows:
  build_and_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main

  checkov:
    jobs:
      - checkov:
          requires:
            - build
